# SIMPLE NEURAL NET : BINARY CLASSIFICATION

In [1]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from sklearn.preprocessing import MinMaxScaler

# Create a synthetic binary classification dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Normalize the data using the min-max scaler
norm = MinMaxScaler().fit(X_train) # This calculates the min and max values of each feature and records them for applicatin to future data
X_train = norm.transform(X_train) # apply the scaler to the training data
X_test = norm.transform(X_test) # apply the scaler to the testing data

# Create and train the neural network model
model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]

# Performance metrics
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)
print(f"Accuracy: {accuracy:.2f}")
print(f"ROC-AUC: {roc_auc:.2f}")


Confusion Matrix:
[[121  24]
 [ 24 131]]

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       145
           1       0.85      0.85      0.85       155

    accuracy                           0.84       300
   macro avg       0.84      0.84      0.84       300
weighted avg       0.84      0.84      0.84       300

Accuracy: 0.84
ROC-AUC: 0.92


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [2]:
X, y

(array([[-0.6693561 , -1.49577819, -0.87076638, ..., -1.26733697,
         -1.2763343 ,  1.01664321],
        [ 0.09337237,  0.78584826,  0.10575379, ..., -0.12270893,
          0.6934308 ,  0.91136272],
        [-0.90579721, -0.60834121,  0.29514098, ...,  0.83049813,
         -0.73733198, -0.5782121 ],
        ...,
        [-0.20013455, -1.46108168,  1.79701652, ..., -1.50280171,
         -1.27473745,  1.60111869],
        [ 0.03935575,  0.24868361, -0.47532342, ...,  0.09912579,
          0.54269228,  1.20827474],
        [ 0.76921528,  0.47076539,  0.16994471, ...,  0.6561162 ,
          0.64333186, -2.02100232]]),
 array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
   

# MULTI CLASS CLASSIFICATION

In [3]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from sklearn.preprocessing import label_binarize
from sklearn.exceptions import UndefinedMetricWarning
import warnings

# Suppress undefined metric warnings
warnings.filterwarnings("ignore", category=UndefinedMetricWarning)

# Create a synthetic multi-class classification dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=3, n_informative=3, n_clusters_per_class=1, random_state=42)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Normalize the data using the min-max scaler
norm = MinMaxScaler().fit(X_train) # This calculates the min and max values of each feature and records them for applicatin to future data
X_train = norm.transform(X_train) # apply the scaler to the training data
X_test = norm.transform(X_test) # apply the scaler to the testing data

# Create and train the neural network model
model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)

# Binarize the labels for multi-class ROC AUC
y_test_binarized = label_binarize(y_test, classes=np.unique(y))
roc_auc = roc_auc_score(y_test_binarized, y_pred_proba, multi_class='ovr')

# Performance metrics
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(f"ROC-AUC: {roc_auc:.2f}")


Confusion Matrix:
[[90  6  9]
 [ 2 84  9]
 [ 7  4 89]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.86      0.88       105
           1       0.89      0.88      0.89        95
           2       0.83      0.89      0.86       100

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300

Accuracy: 0.88
ROC-AUC: 0.98


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [4]:
X,y

(array([[ 0.47404231, -0.17115639, -0.91720268, ...,  0.69606542,
         -0.90385554, -0.46492617],
        [ 0.74390168,  0.6181091 , -0.65280848, ..., -0.83270522,
          0.38124427, -0.14311574],
        [-0.83169229,  0.77588109, -1.68582364, ..., -2.42358281,
          0.38999839,  0.34239935],
        ...,
        [-1.03963394,  2.39191993,  0.26427057, ...,  0.42108499,
         -0.77446164,  0.03647218],
        [ 0.33693433,  0.4313451 ,  2.09873235, ..., -1.26689671,
         -1.38540939,  0.43866796],
        [ 1.17522446,  0.68178318, -1.37225945, ...,  0.80181929,
         -1.11325669, -1.49526606]]),
 array([0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 2, 2, 2,
        1, 1, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 0, 1, 1, 1, 2, 1, 0, 1,
        2, 1, 0, 1, 0, 2, 0, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 1,
        1, 1, 1, 1, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 2, 2, 1, 2,
        0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0, 2, 1,
   

# Differences In Multi Class Vs Binary

    X, y = make_classification(n_samples=1000, n_features=20, n_classes=3, n_informative=3, n_clusters_per_class=1, random_state=42)

    
    from sklearn.exceptions import UndefinedMetricWarning
    import warnings
    warnings.filterwarnings("ignore", category=UndefinedMetricWarning)

    from sklearn.preprocessing import label_binarize
    y_test_binarized = label_binarize(y_test, classes=np.unique(y))
    roc_auc = roc_auc_score(y_test_binarized, y_pred_proba, multi_class='ovr')

        In the binary classification model, the ROC AUC was calculated directly from the binary predictions.
        This change is necessary because ROC AUC calculation for multi-class classification requires binarized labels, and the roc_auc_score method is slightly different (multi_class='ovr' parameter).

    

    

# REGRESSION MODEL

In [5]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Create a synthetic regression dataset
X, y = make_regression(n_samples=1000, n_features=20, n_targets=1, noise=0.1, random_state=42)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Normalize the data using the min-max scaler
norm = MinMaxScaler().fit(X_train) # This calculates the min and max values of each feature and records them for applicatin to future data
X_train = norm.transform(X_train) # apply the scaler to the training data
X_test = norm.transform(X_test) # apply the scaler to the testing data

# Create and train the MLPRegressor model
model = MLPRegressor(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Performance metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")


Mean Squared Error (MSE): 5145.07
R-squared (R2): 0.87


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
