In [1]:
import numpy as np
from numpy import * # Needed for genfromtxt
import pandas as pd # Need for read_csv


# Read Files

In [2]:
# fpath for unsw directory on desktop
fpath = 'C:/Dropbox/Variance/UNSW/ZZSC5836/Snippets/'
fname = fpath+'abalone.csv'

In [3]:

data_in = genfromtxt(fpath+'abalone.csv', delimiter=",") # in case of csv data 
## OR ##
input_df = pd.read_csv(fpath+'abalone.csv', delimiter=",", header=None) # in case of csv data

In [4]:
print('data_in')
print(data_in)
print('input_df')
print(input_df.head())

data_in
[[    nan  0.455   0.365  ...  0.101   0.15   15.    ]
 [    nan  0.35    0.265  ...  0.0485  0.07    7.    ]
 [    nan  0.53    0.42   ...  0.1415  0.21    9.    ]
 ...
 [    nan  0.6     0.475  ...  0.2875  0.308   9.    ]
 [    nan  0.625   0.485  ...  0.261   0.296  10.    ]
 [    nan  0.71    0.555  ...  0.3765  0.495  12.    ]]
input_df
   0      1      2      3       4       5       6      7   8
0  M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15
1  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
2  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
3  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
4  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7


# Numpy Arrays

## Create New Arrays

In [5]:
# Create a numpy matrix and vector of zeros
W1 = np.zeros((5,5)) # Create a numpy matrix of zeros
B1 = np.zeros((1,5)) # Create a numpy vector of zeros

print('\nW1')
print(W1)
print('B1')
print(B1)


W1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
B1
[[0. 0. 0. 0. 0.]]


In [6]:
# Create a numpy matrix and vector of random numbers
# With the values being between -0.5 and 0.5

weights = np.random.rand(5,5)-0.5 # 5x5 matrix of random numbers between -0.5 and 0.5
bias = np.random.rand(1, 5)-0.5 # 1x5 vector of random numbers between -0.5 and 0.5


print('\nWeights')
print(weights)
print('Bias', bias)



Weights
[[ 0.09569426  0.09215963 -0.03844552 -0.20718851  0.23219015]
 [ 0.19852377 -0.43925304 -0.02512835 -0.43672887 -0.19586586]
 [-0.2877745   0.37965678  0.31750945 -0.18861042 -0.24785529]
 [ 0.32639357  0.21262322 -0.03415582 -0.21354047  0.05941082]
 [-0.15436541  0.09510357  0.23269195 -0.07975527 -0.33781019]]
Bias [[-0.13366374  0.32242025 -0.03900415  0.31077965  0.22314774]]


## Reshape an Array

Syntax: 

reshaped_array = old_array.reshape(rows,columns)

MUST declare the array as np array when creating it or reshape method will not run as it is a numpy method.

You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.

In [7]:
## Reshape A 3x3 Array to be a vector
A = np.random.rand(2,2)
print(A,"\n")

# Syntax: reshape(rows, columns)

print(A.reshape(-1,1)) # Reshape to a column vector
print(A.reshape(-1,1).shape) 
print(A.reshape(1,-1))  # Reshape to a row vector
print(A.reshape(1,-1).shape)  


[[0.11465981 0.02840927]
 [0.05212458 0.64751754]] 

[[0.11465981]
 [0.02840927]
 [0.05212458]
 [0.64751754]]
(4, 1)
[[0.11465981 0.02840927 0.05212458 0.64751754]]
(1, 4)


In [8]:
# Go From a 1D Array to a 2D Array
sample_vector = np.array([1,2,3,4,5,6])
print(sample_vector.reshape(2,3)) # Reshape to a 2x3 matrix
print(sample_vector.reshape(2,-1)) # Also reshapes to a 2x3 matrix but calculates the 3 automatically

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


## np.arange: Create a range of values in an array

In [9]:
learn_ratevec = np.arange(0.01, 0.1, 0.02) # create a vector starting at 0.01, ending at 0.1, with a step of 0.02
learn_ratevec

array([0.01, 0.03, 0.05, 0.07, 0.09])

## Print Array at a Certain Precision

In [10]:
## Print an array at a certain precision
np.set_printoptions(precision = 3) #Setting precision for the output

print(weights)

[[ 0.096  0.092 -0.038 -0.207  0.232]
 [ 0.199 -0.439 -0.025 -0.437 -0.196]
 [-0.288  0.38   0.318 -0.189 -0.248]
 [ 0.326  0.213 -0.034 -0.214  0.059]
 [-0.154  0.095  0.233 -0.08  -0.338]]


## Binarize A Vector

In [11]:

y_train = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

threshold = 0  # Define your threshold here
y_train_binary = (y_train > threshold).astype(int)
y_train_binary

array([1, 1, 1, 1, 1])