In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

from keras.utils.np_utils import to_categorical # This does the one hot encoding for us

Keras' to_categorical() is typically used for encoding target labels in neural network models due to its simplicity, while scikit-learn's OneHotEncoder is better suited for preprocessing input features, especially when dealing with complex data types or requiring more flexible preprocessing capabilities.

OneHotEncoder from scikit-learn is more flexible and powerful for preprocessing input features, particularly when dealing with string categorical data. It can handle a broader range of data types and is more versatile in terms of handling unseen categories, dealing with missing values, and integrating into data processing pipelines.
OneHotEncoder can encode multiple columns at once and is generally used in preprocessing steps for machine learning models, especially when dealing with mixed data types (numerical and categorical).

# ONE HOT ENCODING OF OUTPUT DATA

In [2]:

# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# One-hot encode the labels
y_one_hot = to_categorical(y) # This is a Keras function


In [3]:
print("y before one hot encoding: ")
print(y.shape)
print(y)
print("y after one hot encoding: ")
print(y_one_hot.shape)
print(y_one_hot)

y before one hot encoding: 
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
y after one hot encoding: 
(150, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]

In [4]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.3, random_state=42)

# Define the model
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))  # 3 output units for 3 classes

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=10)

# Evaluate the model
_, accuracy = model.evaluate(X_test, y_test)
print(f"Accuracy: {accuracy}")

Epoch 1/100
11/11 [==============================] - 0s 868us/step - loss: 1.6244 - accuracy: 0.5714
Epoch 2/100
11/11 [==============================] - 0s 698us/step - loss: 1.5489 - accuracy: 0.6476
Epoch 3/100
11/11 [==============================] - 0s 698us/step - loss: 1.4719 - accuracy: 0.6476
Epoch 4/100
11/11 [==============================] - 0s 798us/step - loss: 1.4006 - accuracy: 0.6476
Epoch 5/100
11/11 [==============================] - 0s 698us/step - loss: 1.3444 - accuracy: 0.6476
Epoch 6/100
11/11 [==============================] - 0s 798us/step - loss: 1.2947 - accuracy: 0.6476
Epoch 7/100
11/11 [==============================] - 0s 698us/step - loss: 1.2449 - accuracy: 0.6381
Epoch 8/100
11/11 [==============================] - 0s 698us/step - loss: 1.2113 - accuracy: 0.6381
Epoch 9/100
11/11 [==============================] - 0s 798us/step - loss: 1.1791 - accuracy: 0.5905
Epoch 10/100
11/11 [==============================] - 0s 698us/step - loss: 1.1538 - accura

# One hot encoding of an INPUT variable

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# Simulate some data
np.random.seed(42)
age = np.random.randint(18, 70, 1000).reshape(-1, 1)
income = np.random.randint(30000, 70000, 1000).reshape(-1, 1)
membership = np.random.choice(['Silver', 'Gold', 'Platinum'], 1000).reshape(-1, 1)

# One-hot encode the 'membership' feature
encoder = OneHotEncoder(sparse=False)
membership_encoded = encoder.fit_transform(membership)

In [8]:
print("membership before one hot encoding: ")
print(membership.shape)
print(membership[:5])
print("membership after one hot encoding: ")
print(membership_encoded.shape)
print(membership_encoded[:5])

membership before one hot encoding: 
(1000, 1)
[['Platinum']
 ['Silver']
 ['Platinum']
 ['Silver']
 ['Gold']]
membership after one hot encoding: 
(1000, 3)
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [10]:
# Combine the one-hot encoded features back with the rest of the features
X_final = np.hstack((age, income, membership_encoded))

X_final[:5]

array([[5.6000e+01, 6.9650e+04, 0.0000e+00, 1.0000e+00, 0.0000e+00],
       [6.9000e+01, 6.4674e+04, 0.0000e+00, 0.0000e+00, 1.0000e+00],
       [4.6000e+01, 6.5854e+04, 0.0000e+00, 1.0000e+00, 0.0000e+00],
       [3.2000e+01, 3.8152e+04, 0.0000e+00, 0.0000e+00, 1.0000e+00],
       [6.0000e+01, 6.8518e+04, 1.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
# Simulate some target variable (customer satisfaction)
y = np.random.choice([0, 1], 1000)  # Binary outcome for simplicity

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.3, random_state=42)

# Define the model
model = Sequential()
model.add(Dense(10, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=10)

# Evaluate the model
_, accuracy = model.evaluate(X_test, y_test)
print(f"Accuracy: {accuracy}")



Epoch 1/100
70/70 [==============================] - 0s 646us/step - loss: 6340.4180 - accuracy: 0.4871
Epoch 2/100
70/70 [==============================] - 0s 636us/step - loss: 302.6451 - accuracy: 0.5114
Epoch 3/100
70/70 [==============================] - 0s 622us/step - loss: 21.1575 - accuracy: 0.4729
Epoch 4/100
70/70 [==============================] - 0s 651us/step - loss: 15.6993 - accuracy: 0.5014
Epoch 5/100
70/70 [==============================] - 0s 679us/step - loss: 17.3748 - accuracy: 0.4543
Epoch 6/100
70/70 [==============================] - 0s 795us/step - loss: 15.8340 - accuracy: 0.4814
Epoch 7/100
70/70 [==============================] - 0s 680us/step - loss: 18.2467 - accuracy: 0.4800
Epoch 8/100
70/70 [==============================] - 0s 679us/step - loss: 12.5804 - accuracy: 0.4700
Epoch 9/100
70/70 [==============================] - 0s 679us/step - loss: 29.5708 - accuracy: 0.4986
Epoch 10/100
70/70 [==============================] - 0s 679us/step - loss: 19.